### ISSUE TITLE
[FR] support lower versions of obsidian 

### ISSUE THREAD

**Issue by Ravenclawer** [PKM-er/obsidian-zettelkasten-navigation#31]
Sometimes one may remain in lower version of obisidian for better compatibility with old plugins. so it's better for this plugin to support wider ranges of obsidian versions.

**Comment by terrychenzw** [comment]
The minimal obsidian vsersion is 1.5.7 for activating Zettelkasten Navigation plugin. This statement is in the manifest.json file since the earliest public version 0.0.18. 

So if you want to use this plugin, you have to upgrade your Obsidian to 1.5.7 at least.

There may be some new features in the later release using new API from a higher Obsidian version. If in this case, you can just keep using the older release if you don't upgrade your Obsidian. 

Supporting wider ranges of obsidian versions means there are lots of additional efforts for maintaining. I don't think it is the obligation for this free and open source plugin.
